language: ruby
sudo: false

cache:
  bundler: true

matrix:
  fast_finish: true

  include:
    - rvm: 2.2.3
    - rvm: 2.2.3
      gemfile: gemfiles/opal_master.gemfile

script:
  - "bundle exec rake"
